//  SPDX-License-Identifier: GFDL-1.3-or-later
//
//  Copyright © 2000-2022 Erick Gallesio <eg@stklos.net>
//
//           Author: Erick Gallesio [eg@unice.fr]
//    Creation date:  3-Feb-2022 11:16 (eg)
// Last file update: 29-Sep-2022 19:23 (eg)

==  STklos Libraries

This section describes the standard libraries provided by {{stklos}}.

=== The (scheme ...) Libraries

==== {{rseven}} libraries

{{stklos}} offers all the libraries defined by {{rseven}}:

- base
- case-lambda
- char
- complex
- cxr
- eval
- file
- inexact
- lazy
- load
- process-context
- r5rs
- read
- repl
- time
- write

See the <<R7RS>> document for more information.

==== {{rseven}} Large Libraries

{{stklos}} supports some libraries of the (under development) {{rseven}} Large editions.

For now, supported libraries of the *Red edition* are

- list
- charset
- stream
- box
- set
- ilist
- list-queue
- hash-table


=== The (srfi ...) Libraries

All the SRFI supported by {{stklos}} are placed under
the `srfi` meta library and their name is SRFI number. Hence, to use
the exported symbols of {{quick-link-srfi 1}}, you'll have to import the
`(srfi 1)` library.

See  _<<_srfis>>_ for more information

=== The (stklos ...) Libraries

This section describes the standard libraries which are placed under
the `stklos` meta library. Note that {{stklos}} extensions can add
some libraries in the `stklos` meta library; they will be described in
the extension documentation.

==== (stklos itrie) Library

This library was designed by Jerônimo Pellegrini
(https://github.com/jpellegrini[@jpellegrini]).


IMPORTANT: Small description needed

The symbols exported by `(stklos itrie)` are described below:

{{insertdoc 'alist->fxmapping}}
{{insertdoc 'constant-fxmapping}}
{{insertdoc 'constant-iset}}
{{insertdoc 'fxmapping-adjoin}}
{{insertdoc 'fxmapping-contains?}}
{{insertdoc 'fxmapping-empty?}}
{{insertdoc 'fxmapping-height}}
{{insertdoc 'fxmapping-keys}}
{{insertdoc 'fxmapping-mutable?}}
{{insertdoc 'fxmapping-ref/default}}
{{insertdoc 'fxmapping-size}}
{{insertdoc 'fxmapping-values}}
{{insertdoc 'fxmapping-xor}}
{{insertdoc 'fxmapping?}}
{{insertdoc 'iet>=?}}
{{insertdoc 'iset->list}}
{{insertdoc 'iset-adjoin!}}
{{insertdoc 'iset-any?}}
{{insertdoc 'iset-closed-open-interval}}
{{insertdoc 'iset-contains?}}
{{insertdoc 'iset-copy}}
{{insertdoc 'iset-count}}
{{insertdoc 'iset-delete-all!}}
{{insertdoc 'iset-delete-max!}}
{{insertdoc 'iset-disjoint?}}
{{insertdoc 'iset-empty?}}
{{insertdoc 'iset-every?}}
{{insertdoc 'iset-filter!}}
{{insertdoc 'iset-find}}
{{insertdoc 'iset-fold-right}}
{{insertdoc 'iset-for-each}}
{{insertdoc 'iset-height}}
{{insertdoc 'iset-map}}
{{insertdoc 'iset-max}}
{{insertdoc 'iset-member}}
{{insertdoc 'iset-mutable?}}
{{insertdoc 'iset-partition!}}
{{insertdoc 'iset-remove!}}
{{insertdoc 'iset-search!}}
{{insertdoc 'iset-size}}
{{insertdoc 'iset-unfold}}
{{insertdoc 'iset-xor!}}
{{insertdoc 'iset?}}
{{insertdoc 'isubset>=}}
{{insertdoc 'list->iset}}
{{insertdoc 'make-range-iset}}


==== (stklos preproc) Library

IMPORTANT: This library  must be described
