//  SPDX-License-Identifier: GFDL-1.3-or-later
//
//  Copyright © 2000-2024 Erick Gallesio <eg@stklos.net>
//
//           Author: Erick Gallesio [eg@stklos.net]
//    Creation date:  31-Oct-2024 09:48

== Basic Classes

This section describes the basic classes which are inherited by the high level
GTKlos widgets. These classes are not exported by the GTKlos library. However,
since the slots (an their accessor function) are available in the library
widgets, they are exposed here. Furthermore, all the methods described here
are also available in user programs, once the library has been imported.


{{class-doc "gtk-object"}}
=== Class <gtk-object>

The `<gtk-object>` class is the root of the hierarchy of all the GTK object.

{{show-class-table (in-module (stklos gtklos) <gtk-object>)}}


Methods::

- *event-connect* see <<Events, Events>>.
- *event-connect-after* see <<Events, Events>>.

// ======================================================================
{{class-doc "gtk-destroyed-object"}}
=== Class <gtk-destroyed-object>

indexterm:[destroy _method_].
The `<gtk-destroyed-object>` class is the class given to a `<gtk-object>` which
has been destroyed with the <<destroy, *destroy*>> method.

{{show-class-table (in-module (stklos gtklos) <gtk-destroyed-object>)}}


<<<
{{class-doc  "gtk-widget"}}
[%gtk_widget]
=== Class <gtk-widget>

The `<gtk-widget>` is the base class all widgets in GTK derive from.


{{show-class-table (in-module (stklos gtklos) <gtk-widget>)}}

Slots::

- *can-default* specifies whether widget can be a default widget.
- *can-focus* specifies whether widget can own the input focus.
_ *expand* indicates if widget is expanded or not (default to #f).
- *focus-on-click* indicates whether the widget should grab focus when it is
   clicked with the mouse (this slot is only relevant for widgets that can
   take focus).
- *has-default* indicates if  the widget is the default widget.
- *has-focus* indicates if  the widget has the focus.
- *height* contains the actual widget height.
- *height-request* contains the requested widget height.
- *name* denotes the name of the widget. The name of the widget allows you to
   refer to it from a CSS file. See GTK documentation for more information.
- *parent* denotes the parent of the container widget which contain this
   window.  A list can be used when setting the parent of a widget. In this
   case, the first element of the list must be the container in which the
   widget must be added, the rest are the parameters that would be used when
   using the *container-add!* method (see below).
- *sensitive* indicates the if the user can interact with it. If the widget is
   non sensitive, it is grayed out.
- *show* is a read only slots. It indicates if the widget is shown when realized.
  The default value of this slot is `#t`.
- *tooltip* is a string that can the text to be used as a tooltip for the
  created widget.
- *visible* is a boolean to set/unset the visibility of the widget.
- *wid* is a {{stklos}} slot. It contains the low level GTK widget which
   implements the high level GTKlos object. Its value is generally set in the
   <<realize-widget, *realize-widget* method>>.  Normal user program shouldn't
   change the value of this slot.
- *width* contains the actual widget width.
- *with-request* contains the requested widget width.

[#realize-widget]
Methods::
[#destroy]
- *container-add!* {{see-container-add}}
- *container-info* returns some information on the way the widget has been
   added to its container as a list. If the widget has no parent, it returns
   `#f`.
- *container-remove!* {{see-container-remove}}
- *destroy* permits to destroy the widget.  When a widget is destroyed, its
   class is changed to `<destroyed-gtk-object>`.
- *internal-arrange-widget* is a hook called when the widget is
   initialized. Most of the time it does nothing.
- *realize-widget* is the method called to create a low level GTK widget, and
   initialize it properly. Each widget has it own `realize-widget`. For
   `<gtk-widget>`, it does nothing.


{{class-doc  "gtk-container"}}
=== Class <gtk-container>


The `<gtk-container>` class is inherited by all the container widgets.


{{show-class-table (in-module (stklos gtklos) <gtk-container>)}}

The direct methods of this class are described in the section about
<<class-gtk-widget, *<gtk-widget>* class>>.

[#container-add!]
Methods::
[#container-remove!]

- *container-add!*  is the method used to add a widget to a container. Its
   first argument is the container widget and its second argument is the
   widget to add to the container. Subsequent parameters depend of the
   container (each container has its own conventions to add a component to
   it).
- *container-remove!* permit to remove the widget form it container. The
   widget is not destroyed.
- *destroy* permits to destroy the widget (and all its children).  When a
   widget is destroyed, its class is changed to `<destroyed-gtk-object>`.


<<<

// ----------------------------------------------------------------------
{{class-doc  "gtk-misc"}}
=== Class <gtk-misc>

This class factorizes properties which are common between the label and image
widgets.

{{show-class-table (in-module (stklos gtklos) <gtk-misc>)}}

Slots::

- *xalign* is the horizontal alignment of the widget, from 0.0 (left) to 1.0
   (right).
- *xpad* is the horizontal amount of padding for the widget.
- *yalign* is the vertical alignment of the widget , from 0.0 (top) to 1.0
   (bottom).
- *ypad* is the vertical amount of padding for the widget.


{{class-doc  "gtk-orientable"}}
=== Class <gtk-orientable>

The class `<gtk-orientable>` is inherited by classes which can be horizontally or vertically oriented.

{{show-class-table (in-module (stklos gtklos) <gtk-orientable>)}}

Method::

- *orientation* indicates the orientation of the widget. It's value is a
symbol whose value can be `horitontal` or `vertical`.


<<<
// ======================================================================
{{class-doc  "gtk-menu-shell"}}
=== Class <gtk-menu-shell>

The class `<gtk-menu-shell>` is a base class. It is the ancestor of the classes
`<menu>` and `<menu-bar>`.

{{show-class-table (in-module (stklos gtklos) <gtk-menu-shell>)}}


// ======================================================================
{{class-doc  "gtk-menu-item"}}
=== Class <gtk-menu-item>

The class `<gtk-menu-item>` is inherited by menu item classes which can hav an
associated callback .

{{show-class-table (in-module (stklos gtklos) <gtk-menu-item>)}}

Method::

- *command* contains the callback associated to the menu item (see <<Events,
   Events>>).
