#!/bin/sh
#
# A simple script to run the GTklos demos
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date: 15-Jul-2021 19:39
# Last file update: 16-Jul-2021 10:20 (eg)

# Change the directory because the "See code" buttons in each demos search in
# the current directory only
cd demos

# Assume that the user has perhaps not yet installed STklos, and that the
# stklos-script wrapper is not available.
PATH=../../../utils:$PATH

# Run the demos script
./demos
