#!/bin/sh
#
# A simple script to run the GTklos demos
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date: 15-Jul-2021 19:39

# Change the directory because the "See code" buttons in each demos search in
# the current directory only
cd demos

# Assume that the user has perhaps not yet installed STklos, and that the
# stklos-script wrapper is not available.
top=../../..
PATH=${top}/src:$PATH

# Run the demos script. Since STklos is perhaps not yet installed. Don't use
# stklos-script and call directly stklos on compiled files
stklos -f ./demos
