#!/usr/bin/env bash
#
#  make-push-id      -- Build an id for a given push
#
# Copyright © 2018 Erick Gallesio - I3S-CNRS/Polytech Nice-Sophia <eg@unice.fr>
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date:  3-Jul-2018 18:03
# Last file update:  3-Jul-2018 18:09 (eg)

current=$(expr $(date "+%s") - 1500000000)
signature=$(printf "%x" $current)
sed -i -e '/GIT_PUSH_ID/s=".*"="'$signature'"=' src/extraconf.h.in
printf "   "; grep GIT_PUSH_ID src/extraconf.h.in

