#!/bin/sh
#
# Date correction of iportant files to avoid the need of automake GNU/tools 
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date: 26-Nov-2019 17:56
# Last file update: 26-Nov-2019 18:01 (eg)

now=`date +"%Y%m%d%H%M.%S"`

echo -n "Touching some files ... "

find . -name aclocal.m4      \
    -o -name Makefile.am     \
    -o -name configure       \
    -o -name Makefile.in     \
    -exec touch -t ${now} {} \;

echo "done."