#!/bin/sh
#
# tmpgenlex	-- A temporary script used when bootstraping the system
#
# Copyright © 2011 Erick Gallesio - I3S-CNRS/ESSI <eg@unice.fr>
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
# USA.
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date:  1-Jan-2002 18:57 (eg)
#


STKLOS_LOAD_PATH="../lib"
export STKLOS_LOAD_PATH 

../src/stklos -c -q -b ../src/boot.img -f ../utils/stklos-genlex -- $*


