SHARED = lib.[DYNEXT]

all: $(SHARED) runtests

clean:
	rm -f lib.o $(SHARED) runtests

lib.o: lib.c
	gcc  [CFLAGS] [DYNCFLAGS] -c lib.c -o lib.o

$(SHARED): lib.o
	[BUILDSHARED] $(SHARED) lib.o

runtests: runtests.c $(SHARED) ../lib/libcinvoke.a
	gcc [CFLAGS] -o runtests runtests.c -L../lib -I../lib [LIBDL] -lcinvoke -lm
