/*
 * types.c	-- Build source of the mpi-types.h file
 * 
 * Copyright © 2009 Erick Gallesio - Polytech'Nice-Sophia <eg@unice.fr>
 * 
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
 * USA.
 * 
 *           Author: Erick Gallesio [eg@unice.fr]
 *    Creation date: 27-Oct-2009 21:19 (eg)
 * Last file update: 27-Oct-2009 22:03 (eg)
 */

#include <stdio.h>
#include <stdlib.h>

void write_code(char *type1, int len1, char *max1,
		char* type2, int len2, char* max2)
{
  printf("/* File definitions generated by program. DO NOT edit */\n");
  printf("\n");
  printf("typedef char  mp_sign;\n");
  printf("typedef %s mp_digit;  /* %d byte type */\n", type1, len1);
  printf("typedef %s mp_word;   /* %d byte type */\n", type2, len2);
  printf("typedef unsigned int mp_size;\n");
  printf("typedef int mp_err;\n");
  printf("\n");
  printf("#define MP_DIGIT_BIT       (CHAR_BIT*sizeof(mp_digit))\n");
  printf("#define MP_DIGIT_MAX       %s\n", max1);
  printf("#define MP_WORD_BIT        (CHAR_BIT*sizeof(mp_word))\n");
  printf("#define MP_WORD_MAX        %s\n", max2);
  printf("\n");
  printf("#define RADIX              (MP_DIGIT_MAX+1)\n");
  printf("\n");
  printf("#define MP_DIGIT_SIZE      %d\n", len1);
  printf("#define DIGIT_FMT          \"%%0%dX\"\n", len2);
}


void generate_file(int ch, int sh, int in , int lo)
{
  if ((ch == 1) && (sh == 2) && (in == 4) && (lo == 4)) {
    /* Classical 32 bits */
    write_code("unsigned short", 2, "USHRT_MAX", 
	       "unsigned int",   4, "UINT_MAX");
  }
  else if ((ch == 1) && (sh == 2) && (in == 4) && (lo == 8)) {
    /* Classical 64 bits */
    write_code("unsigned int",  4, "UINT_MAX",
	       "unsigned long", 8, "ULONG_MAX");
  }
  else {
    fprintf(stderr, "Cannot produce code for %d %d %d %d\n", ch, sh, in, lo);
    exit(1);
  }
}
  
int main() 
{
  generate_file(sizeof(unsigned char),
		sizeof(unsigned short),
		sizeof(unsigned int),
		sizeof(unsigned long));
  return 0;
}
